version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Working with AWS CLI
          command: |
            AWS_REGION=us-east-1
            aws s3 ls s3://
            echo "listing S3 Buckets...."
            cat projects/copytoec2.txt
